/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    developers: Developer;
    communities: Community;
    lenders: Lender;
    agents: Agent;
    articles: Article;
    leads: Lead;
    media: Media;
    users: User;
    'internal-project-universe': InternalProjectUniverse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    communities: CommunitiesSelect<false> | CommunitiesSelect<true>;
    lenders: LendersSelect<false> | LendersSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'internal-project-universe': InternalProjectUniverseSelect<false> | InternalProjectUniverseSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-stats': SiteStat;
    'mortgage-constants': MortgageConstant;
    'legal-entity': LegalEntity;
  };
  globalsSelect: {
    'site-stats': SiteStatsSelect<false> | SiteStatsSelect<true>;
    'mortgage-constants': MortgageConstantsSelect<false> | MortgageConstantsSelect<true>;
    'legal-entity': LegalEntitySelect<false> | LegalEntitySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * A project cannot be published without media licence, Trakheesi permit, our verdict, and complete core facts. The publish gate lists anything missing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  slug: string;
  name: string;
  subCommunity: string;
  community?: (number | null) | Community;
  /**
   * Decides which advertising rules apply. UAE listings require a Trakheesi permit; other markets have their own regime.
   */
  country: 'AE' | 'OM' | 'GE' | 'TH' | 'ID' | 'EG' | 'US' | 'CY';
  /**
   * Emirate, governorate, province or state, depending on the country.
   */
  region:
    | 'Dubai'
    | 'Abu Dhabi'
    | 'Ras Al Khaimah'
    | 'Sharjah'
    | 'Ajman'
    | 'UAQ'
    | 'Fujairah'
    | 'Muscat'
    | 'Dhofar'
    | 'Musandam'
    | 'Al Batinah North'
    | 'Al Batinah South'
    | 'Tbilisi'
    | 'Adjara'
    | 'Imereti'
    | 'Kvemo Kartli'
    | 'Bangkok'
    | 'Phuket'
    | 'Chon Buri'
    | 'Chiang Mai'
    | 'Surat Thani'
    | 'Bali'
    | 'Jakarta'
    | 'West Java'
    | 'East Java'
    | 'Matrouh (North Coast)'
    | 'Cairo'
    | 'Giza'
    | 'Red Sea'
    | 'South Sinai'
    | 'Florida'
    | 'Texas'
    | 'Georgia'
    | 'New York'
    | 'California'
    | 'Arizona'
    | 'Limassol'
    | 'Paphos'
    | 'Larnaca'
    | 'Nicosia';
  developer?: (number | null) | Developer;
  status: 'pre-launch' | 'launched' | 'under-construction' | 'nearing-handover' | 'handed-over' | 'sold-out';
  propertyTypes: (
    'Apartment' | 'Penthouse' | 'Townhouse' | 'Villa' | 'Sky Villa' | 'Duplex' | 'Mansion' | 'Hotel Room' | 'Office'
  )[];
  /**
   * 0 = studio
   */
  bedroomsMin: number;
  bedroomsMax: number;
  priceFromAED: number;
  priceToAED?: number | null;
  sizeFromSqft: number;
  sizeToSqft?: number | null;
  /**
   * Computed from price/size when left empty; override if needed.
   */
  pricePerSqftFrom?: number | null;
  paymentPlan: {
    /**
     * "60/40", "80/20", "50/50 post-handover"
     */
    label: string;
    duringConstructionPct?: number | null;
    onHandoverPct?: number | null;
    postHandoverPct?: number | null;
    postHandoverMonths?: number | null;
    milestones?:
      | {
          label: string;
          pct: number;
          /**
           * e.g. "On booking", "30% construction", "Handover"
           */
          trigger: string;
          id?: string | null;
        }[]
      | null;
  };
  handoverQuarter?: ('Q1' | 'Q2' | 'Q3' | 'Q4') | null;
  handoverYear?: number | null;
  launchDate?: string | null;
  /**
   * DLD/RERA project registration
   */
  dldProjectNumber?: string | null;
  escrowAccountConfirmed?: boolean | null;
  oqoodEligible?: boolean | null;
  freehold?: boolean | null;
  /**
   * Auto-set from AED 2M threshold when left unset; override allowed.
   */
  goldenVisaEligible?: boolean | null;
  serviceChargeEstimateAEDPerSqft?: number | null;
  /**
   * Supplied by the feed or the developer pack.
   */
  amenities?: string[] | null;
  /**
   * e.g. "Semi-furnished", as stated by the developer.
   */
  furnishing?: string | null;
  /**
   * Construction progress, where the source reports it.
   */
  readinessPct?: number | null;
  /**
   * Walk/drive times used by the location section (§6.6).
   */
  nearbyPlaces?:
    | {
        name: string;
        distanceKm?: number | null;
        minutes?: number | null;
        id?: string | null;
      }[]
    | null;
  assignmentAllowed?: boolean | null;
  assignmentMinPaidPct?: number | null;
  developerNocFeeAED?: number | null;
  alcazarStatus: 'shortlisted' | 'monitoring' | 'declined';
  /**
   * Our own written view, 80–150 words. Never sourced from a competitor's text. This is the product.
   */
  alcazarVerdict?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The eight tests. 1 = fail, 5 = strong.
   */
  alcazarFilterScores?: {
    developerRecord?: number | null;
    regulatoryStanding?: number | null;
    priceVsComparables?: number | null;
    paymentStructure?: number | null;
    supplyInWindow?: number | null;
    exitTerms?: number | null;
    runningCost?: number | null;
    unitQuality?: number | null;
  };
  /**
   * Factual test outcomes only — no characterisations. Legal review required before any declined page goes public.
   */
  declineReason?: string | null;
  /**
   * Render a public stripped page for this declined project. Case-by-case decision (§6).
   */
  declinePublic?: boolean | null;
  mortgageable?: ('yes' | 'at-handover-only' | 'no' | 'unknown') | null;
  lendersFinancing?: (number | Lender)[] | null;
  media?: {
    hero?: (number | null) | Media;
    gallery?: (number | Media)[] | null;
    floorPlans?: (number | Media)[] | null;
    brochure?: (number | null) | Media;
    video?: string | null;
  };
  /**
   * §11.9 — no image renders without a licence. Log the developer permission grant in the note.
   */
  mediaLicence: 'developer-supplied' | 'own-photography' | 'unlicensed';
  /**
   * Contact + date of the permission grant.
   */
  mediaLicenceNote?: string | null;
  /**
   * §11.1 — required before a UAE listing can publish. Renders on the page.
   */
  trakheesiPermitNumber?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Sort order for the home shortlist strip.
   */
  editorialOrder?: number | null;
  /**
   * Development seed data — excluded from production builds.
   */
  isFixture?: boolean | null;
  unitTypes?:
    | {
        label: string;
        bedrooms: number;
        bathrooms?: number | null;
        sizeSqftMin?: number | null;
        sizeSqftMax?: number | null;
        priceFromAED?: number | null;
        floorPlan?: (number | null) | Media;
        availability?: ('available' | 'limited' | 'sold-out') | null;
        view?: string | null;
        orientation?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communities".
 */
export interface Community {
  id: number;
  slug: string;
  name: string;
  country: 'AE' | 'OM' | 'GE' | 'TH' | 'ID' | 'EG' | 'US' | 'CY';
  region:
    | 'Dubai'
    | 'Abu Dhabi'
    | 'Ras Al Khaimah'
    | 'Sharjah'
    | 'Ajman'
    | 'UAQ'
    | 'Fujairah'
    | 'Muscat'
    | 'Dhofar'
    | 'Musandam'
    | 'Al Batinah North'
    | 'Al Batinah South'
    | 'Tbilisi'
    | 'Adjara'
    | 'Imereti'
    | 'Kvemo Kartli'
    | 'Bangkok'
    | 'Phuket'
    | 'Chon Buri'
    | 'Chiang Mai'
    | 'Surat Thani'
    | 'Bali'
    | 'Jakarta'
    | 'West Java'
    | 'East Java'
    | 'Matrouh (North Coast)'
    | 'Cairo'
    | 'Giza'
    | 'Red Sea'
    | 'South Sinai'
    | 'Florida'
    | 'Texas'
    | 'Georgia'
    | 'New York'
    | 'California'
    | 'Arizona'
    | 'Limassol'
    | 'Paphos'
    | 'Larnaca'
    | 'Nicosia';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lat?: number | null;
  lng?: number | null;
  avgPricePerSqft?: number | null;
  avgRentalYieldPct?: number | null;
  transportNotes?: string | null;
  schoolsNotes?: string | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Shown in gallery caption strips, e.g. 'Render: developer name'.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: number;
  slug: string;
  name: string;
  logo?: (number | null) | Media;
  foundedYear?: number | null;
  headquarters?: string | null;
  completedUnits?: number | null;
  projectsDelivered?: number | null;
  /**
   * Across delivered projects. Source it — this renders publicly on the track record card.
   */
  averageHandoverSlippageMonths?: number | null;
  deliveryTrackRecord?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  alcazarPanelStatus: 'active' | 'selective' | 'not-on-panel';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lenders".
 */
export interface Lender {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  maxLtvResidentPct?: number | null;
  maxLtvNonResidentPct?: number | null;
  financesOffplan?: boolean | null;
  minMonthlyIncomeAED?: number | null;
  minMonthlyIncomeNonResidentUSD?: number | null;
  indicativeFixedRatePct?: number | null;
  fixedPeriodYears?: number | null;
  notes?: string | null;
  onPanel?: boolean | null;
  /**
   * §11.10 — no rate or LTV renders publicly without an effective date and source.
   */
  ratesEffectiveFrom?: string | null;
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  slug: string;
  name: string;
  role: string;
  /**
   * RERA broker number — §11.2, renders on the profile and every attributed listing.
   */
  brn: string;
  languages?: string[] | null;
  specialisms?: string[] | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * E.164, e.g. +9715...
   */
  whatsapp?: string | null;
  email?: string | null;
  calendlyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  title: string;
  category: 'market' | 'mortgage' | 'community' | 'developer' | 'guide';
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Agent;
  publishedAt?: string | null;
  updatedAt2?: string | null;
  relatedProjects?: (number | Project)[] | null;
  relatedCommunities?: (number | Community)[] | null;
  /**
   * Rendered with FAQPage schema markup (§10).
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PDPL: lawful basis is captured per submission; deletion requests are honoured here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  whatsappConsent?: boolean | null;
  marketingConsent?: boolean | null;
  residencyStatus?: ('uae-resident' | 'non-resident' | 'uae-national') | null;
  budgetBandAED?: string | null;
  purpose?: ('investment' | 'end-use' | 'both') | null;
  financeNeeded?: boolean | null;
  sourceProject?: (number | null) | Project;
  sourcePage?: string | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  locale?: string | null;
  currency?: string | null;
  message?: string | null;
  crmSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Internal competitive intelligence from the discovery crawl. Never published, never rendered. Facts only — no descriptions, no media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-project-universe".
 */
export interface InternalProjectUniverse {
  id: number;
  fingerprint: string;
  projectName: string;
  developerName?: string | null;
  community?: string | null;
  emirate?: string | null;
  /**
   * As published, e.g. 'Q4 2027'
   */
  handover?: string | null;
  paymentPlanLabel?: string | null;
  priceFromAED?: number | null;
  propertyTypes?: string[] | null;
  bedroomsRange?: string | null;
  sourceUrl: string;
  sourceHost: string;
  firstSeen: string;
  lastSeen: string;
  /**
   * Always false. Enforced by hook and database constraint.
   */
  publishable?: boolean | null;
  /**
   * Sales-floor triage. 'Worth sourcing' means request the developer pack (Track B).
   */
  triagedAs?: ('untriaged' | 'worth-sourcing' | 'ignore') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'communities';
        value: number | Community;
      } | null)
    | ({
        relationTo: 'lenders';
        value: number | Lender;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'internal-project-universe';
        value: number | InternalProjectUniverse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  subCommunity?: T;
  community?: T;
  country?: T;
  region?: T;
  developer?: T;
  status?: T;
  propertyTypes?: T;
  bedroomsMin?: T;
  bedroomsMax?: T;
  priceFromAED?: T;
  priceToAED?: T;
  sizeFromSqft?: T;
  sizeToSqft?: T;
  pricePerSqftFrom?: T;
  paymentPlan?:
    | T
    | {
        label?: T;
        duringConstructionPct?: T;
        onHandoverPct?: T;
        postHandoverPct?: T;
        postHandoverMonths?: T;
        milestones?:
          | T
          | {
              label?: T;
              pct?: T;
              trigger?: T;
              id?: T;
            };
      };
  handoverQuarter?: T;
  handoverYear?: T;
  launchDate?: T;
  dldProjectNumber?: T;
  escrowAccountConfirmed?: T;
  oqoodEligible?: T;
  freehold?: T;
  goldenVisaEligible?: T;
  serviceChargeEstimateAEDPerSqft?: T;
  amenities?: T;
  furnishing?: T;
  readinessPct?: T;
  nearbyPlaces?:
    | T
    | {
        name?: T;
        distanceKm?: T;
        minutes?: T;
        id?: T;
      };
  assignmentAllowed?: T;
  assignmentMinPaidPct?: T;
  developerNocFeeAED?: T;
  alcazarStatus?: T;
  alcazarVerdict?: T;
  alcazarFilterScores?:
    | T
    | {
        developerRecord?: T;
        regulatoryStanding?: T;
        priceVsComparables?: T;
        paymentStructure?: T;
        supplyInWindow?: T;
        exitTerms?: T;
        runningCost?: T;
        unitQuality?: T;
      };
  declineReason?: T;
  declinePublic?: T;
  mortgageable?: T;
  lendersFinancing?: T;
  media?:
    | T
    | {
        hero?: T;
        gallery?: T;
        floorPlans?: T;
        brochure?: T;
        video?: T;
      };
  mediaLicence?: T;
  mediaLicenceNote?: T;
  trakheesiPermitNumber?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  editorialOrder?: T;
  isFixture?: T;
  unitTypes?:
    | T
    | {
        label?: T;
        bedrooms?: T;
        bathrooms?: T;
        sizeSqftMin?: T;
        sizeSqftMax?: T;
        priceFromAED?: T;
        floorPlan?: T;
        availability?: T;
        view?: T;
        orientation?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  logo?: T;
  foundedYear?: T;
  headquarters?: T;
  completedUnits?: T;
  projectsDelivered?: T;
  averageHandoverSlippageMonths?: T;
  deliveryTrackRecord?: T;
  alcazarPanelStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communities_select".
 */
export interface CommunitiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  country?: T;
  region?: T;
  description?: T;
  lat?: T;
  lng?: T;
  avgPricePerSqft?: T;
  avgRentalYieldPct?: T;
  transportNotes?: T;
  schoolsNotes?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lenders_select".
 */
export interface LendersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  maxLtvResidentPct?: T;
  maxLtvNonResidentPct?: T;
  financesOffplan?: T;
  minMonthlyIncomeAED?: T;
  minMonthlyIncomeNonResidentUSD?: T;
  indicativeFixedRatePct?: T;
  fixedPeriodYears?: T;
  notes?: T;
  onPanel?: T;
  ratesEffectiveFrom?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  brn?: T;
  languages?: T;
  specialisms?: T;
  photo?: T;
  bio?: T;
  whatsapp?: T;
  email?: T;
  calendlyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  publishedAt?: T;
  updatedAt2?: T;
  relatedProjects?: T;
  relatedCommunities?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  whatsappConsent?: T;
  marketingConsent?: T;
  residencyStatus?: T;
  budgetBandAED?: T;
  purpose?: T;
  financeNeeded?: T;
  sourceProject?: T;
  sourcePage?: T;
  utm?: T;
  locale?: T;
  currency?: T;
  message?: T;
  crmSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-project-universe_select".
 */
export interface InternalProjectUniverseSelect<T extends boolean = true> {
  fingerprint?: T;
  projectName?: T;
  developerName?: T;
  community?: T;
  emirate?: T;
  handover?: T;
  paymentPlanLabel?: T;
  priceFromAED?: T;
  propertyTypes?: T;
  bedroomsRange?: T;
  sourceUrl?: T;
  sourceHost?: T;
  firstSeen?: T;
  lastSeen?: T;
  publishable?: T;
  triagedAs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats".
 */
export interface SiteStat {
  id: number;
  reviewsTracked?: boolean | null;
  launchesReviewedThisYear?: number | null;
  reachedShortlistThisYear?: number | null;
  marketStats?:
    | {
        value: string;
        label: string;
        source: string;
        asOf: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * CBUAE caps and DLD fee schedule. Verify against current circulars before launch — these render publicly with the effective date.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mortgage-constants".
 */
export interface MortgageConstant {
  id: number;
  effectiveFrom: string;
  sourceNote: string;
  ltv: {
    nationalFirstLe5MPct: number;
    nationalFirstGt5MPct: number;
    expatFirstLe5MPct: number;
    expatFirstGt5MPct: number;
    secondPropertyPct: number;
    nonResidentPct: number;
    offPlanPct: number;
    firstPropertyThresholdAED: number;
  };
  dbr: {
    expatPct: number;
    nationalPct: number;
  };
  tenure: {
    maxYears: number;
    maxAgeSalaried: number;
    maxAgeSelfEmployed: number;
  };
  fees: {
    dldTransferPct: number;
    dldAdminAED: number;
    mortgageRegistrationPct: number;
    mortgageRegistrationAdminAED: number;
    bankArrangementPct: number;
    valuationMinAED: number;
    valuationMaxAED: number;
    trusteeMinAED: number;
    trusteeMaxAED: number;
    agencyCommissionPct: number;
    lifeInsurancePctAnnual: number;
    propertyInsurancePctAnnual: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Appears in the footer of every page and on every property advert. An ORN is publicly searchable in the DLD register, so whatever is entered here is discoverable regardless of how it is displayed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-entity".
 */
export interface LegalEntity {
  id: number;
  /**
   * The consumer-facing brand. Used everywhere on the site.
   */
  brandName: string;
  /**
   * The company that holds the brokerage licence. Required on adverts under RERA rules — see displayMode.
   */
  licensedEntityName?: string | null;
  /**
   * Brand-only omits the licence holder's name. The ORN still resolves to it publicly, and RERA advertising rules expect the broker to be identified — take legal advice before using it.
   */
  displayMode: 'brand-with-licence-line' | 'brand-only';
  /**
   * RERA Office Registration Number
   */
  orn?: string | null;
  /**
   * DED trade licence number
   */
  tradeLicence?: string | null;
  dldBrokerRegistration?: string | null;
  /**
   * The registered office address shown on the site.
   */
  address?: string | null;
  city?: string | null;
  phone?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats_select".
 */
export interface SiteStatsSelect<T extends boolean = true> {
  reviewsTracked?: T;
  launchesReviewedThisYear?: T;
  reachedShortlistThisYear?: T;
  marketStats?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        asOf?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mortgage-constants_select".
 */
export interface MortgageConstantsSelect<T extends boolean = true> {
  effectiveFrom?: T;
  sourceNote?: T;
  ltv?:
    | T
    | {
        nationalFirstLe5MPct?: T;
        nationalFirstGt5MPct?: T;
        expatFirstLe5MPct?: T;
        expatFirstGt5MPct?: T;
        secondPropertyPct?: T;
        nonResidentPct?: T;
        offPlanPct?: T;
        firstPropertyThresholdAED?: T;
      };
  dbr?:
    | T
    | {
        expatPct?: T;
        nationalPct?: T;
      };
  tenure?:
    | T
    | {
        maxYears?: T;
        maxAgeSalaried?: T;
        maxAgeSelfEmployed?: T;
      };
  fees?:
    | T
    | {
        dldTransferPct?: T;
        dldAdminAED?: T;
        mortgageRegistrationPct?: T;
        mortgageRegistrationAdminAED?: T;
        bankArrangementPct?: T;
        valuationMinAED?: T;
        valuationMaxAED?: T;
        trusteeMinAED?: T;
        trusteeMaxAED?: T;
        agencyCommissionPct?: T;
        lifeInsurancePctAnnual?: T;
        propertyInsurancePctAnnual?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-entity_select".
 */
export interface LegalEntitySelect<T extends boolean = true> {
  brandName?: T;
  licensedEntityName?: T;
  displayMode?: T;
  orn?: T;
  tradeLicence?: T;
  dldBrokerRegistration?: T;
  address?: T;
  city?: T;
  phone?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}